### ISSUE TITLE
Unable to create Flex Flow in the Go SDK due to incorrectly generated parameter names

### ISSUE THREAD

**Issue by RJPearson94** [twilio/twilio-oai-generator#27]
Hey, 

First of all, I just want to say this looks great. Super excited to see the Go SDK enter pilot.

I have been trying out the Go SDK and I ran into an issue when trying to create a Flex Flow. When attempting to create a Flex Flow with the code below

```
package main

import (
    "log"
    "os"

    "github.com/twilio/twilio-go/twilio"
    openapi "github.com/twilio/twilio-go/twilio/rest/flex/v1"
)

func main() {
    accountSid := os.Getenv("TWILIO_ACCOUNT_SID")
    authToken := os.Getenv("TWILIO_AUTH_TOKEN")
    client := twilio.NewClient(accountSid, authToken)

    resp, err := client.FlexV1.CreateFlexFlow(&openapi.CreateFlexFlowParams{
        FriendlyName:    PtrString("Test Flow"),
        ChatServiceSid:  PtrString(os.Getenv("TWILIO_FLEX_CHANNEL_SERVICE_SID")),
        ChannelType:     PtrString("web"),
        IntegrationType: PtrString("external"),
        IntegrationUrl:  PtrString("https://test.com/external"),
    })

    if err != nil {
        log.Panic(err.Error())
    }

    log.Printf("SID: %s", StringValue(resp.Sid))
}

// PtrString is a utility function for obtaining a pointer for a value
func PtrString(value string) *string {
    return &value
}

// StringValue is a utility function for dereferencing a pointer 
func StringValue(ptr *string) string {
    return *ptr
}
```

I get the following error

```
2021/04/15 02:17:47 Status: 400 - ApiError 45004: WebhookUrl is missing (null) More info: https://www.twilio.com/docs/errors/45004
panic: Status: 400 - ApiError 45004: WebhookUrl is missing (null) More info: https://www.twilio.com/docs/errors/45004
```

I was looking through the Go SDK and I noticed the parameter name for Integration URL is incorrect (https://github.com/twilio/twilio-go/blob/main/twilio/rest/flex/v1/api_default.go#L199). The name is set to `IntegrationUrl` whereas in the docs (https://www.twilio.com/docs/flex/developer/messaging/api/flow#create-a-flex-flow-with-studio) and OpenAPI template (https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_flex_v1.yaml#L771) the parameter name is `Integration.Url`. 

This is also applicable to `IntegrationFlowSid`, `IntegrationWorkspaceSid`, `IntegrationWorkflowSid`, `IntegrationChannel`, `IntegrationTimeout`, `IntegrationPriority` and `IntegrationCreationOnMessage` (https://github.com/twilio/twilio-go/blob/main/twilio/rest/flex/v1/api_default.go#L180-L206)

Looking through the generator code in the `api.mustache` template I saw the parameter name is used as the prefix for the Params struct name (https://github.com/twilio/twilio-oai-generator/blob/main/src/main/resources/twilio-go/api.mustache#L34) and as the parameter name which is set as the key in the url Values at https://github.com/twilio/twilio-oai-generator/blob/main/src/main/resources/twilio-go/api.mustache#L81 and https://github.com/twilio/twilio-oai-generator/blob/main/src/main/resources/twilio-go/api.mustache#L84 

The parameter name is modified in `AbstractTwilioGoGenerator` class to remove certain characters (https://github.com/twilio/twilio-oai-generator/blob/main/src/main/java/com/twilio/oai/AbstractTwilioGoGenerator.java#L59) including full stops/ periods. 

The parameter name in the url Values should be the original name, specified in the OpenAPI template and not the modified value. I can't remember which other API's use full stops/ periods in their parameter names but I don't believe it's limited to just Flex Flows. I could be wrong though.

I'm not sure if the problem can be fixed in this repo or would require any upstream changes but I thought this would be the most sensible place to raise it. I’m not sure on the best way to address this issue but I am happy to make any necessary changes.

I didn't see a bug template in the list and I wasn't sure if this was a support case or not, so apologies if this is the wrong place to raise this issue or if it is in the wrong format.

Thanks
Rob

**Comment by shwetha-manvinkurke** [comment]
@RJPearson94 Thank you for raising the issue and the detailed troubleshooting! You are welcome to submit a PR with the changes here. `data.Set("{{baseName}}")` instead of the `paramName` should potentially fix this issue and the issue has been added to the backlog to be prioritized in the meantime.

**Comment by RJPearson94** [comment]
Hi @shwetha-manvinkurke, thanks for the quick response. I'll take a look at the `baseName`, I did briefly look at it last night but not in too much detail. If I find a solution I'll raise a PR

**Comment by RJPearson94** [comment]
changing the mustache template to use baseName instead of the paramName was the fix, apologies for not spotting that last night and raising the PR too. I have raised the PR now.
